
; The configuration is stored in an ini-like syntax.
; The global section defines the indicator ID used for styling.
; A line starting with a semicolon is treated as a comment line, NO inline comment is supported.
; ONLY styling of the text foreground color is supported.
; Updates to the configuration are read when the file is saved and applied immediately
; when the buffer of the configured lexer is reactivated.
[global]
; The ID of the indicator used to style the matches.
; If there are conflicts with indicators used by Npp or other plugins, change this value.
; The expected range is between 0 and 35; according to Scinitilla.
indicator_id=0
; If specifying an offset, it will affect both the start and end lines.
; For example, if the currently visible lines range from 100 to 150 and an offset=10 is given,
; the regular expressions are matched with the text from lines 90 to 160.
offset=0
; The ID of the style used to display regex errors.
; If there are conflicts with other styles used by Npp or other plugins, change this value.
; The expected range is between 0 and 255; according to Scinitilla.
regex_error_style_id=30
; The color used by the style.
; For an explanation of how this color can be defined, see the following description of the regexes and their colors.
regex_error_color=0x756ce0

; Each configured lexer must have a section with its name,
; (NOTE: use the menu function "Enhance current language" as it takes care of the correct naming)
; followed by one or more lines with the syntax
; color = regular expression.
; A color is a number in the range 0 - 16777215.
; The notation is either pure digits or a hex notation starting with 0x or #,
; such as 0xff00ff or #ff00ff.
; Please note:
; * red goes in the lowest byte (0x0000FF)
; * green goes in the center byte (0x00FF00)
; * blue goes in the biggest byte (0xFF0000)
; * this BGR order might conflict with your expectation of RGB order.
; * see Microsoft COLORREF documentation https://docs.microsoft.com/en-us/windows/win32/gdi/colorref

; The optional line of excluded_styles is expected in the form of
; excluded_styles = 1,2,3,4,5 ...
; The numbers refer to the style IDs used by the lexer and
; can be taken from the file stylers.xml or USED_THEME_NAME.xml
; and in case of UDLs the mapping is only described in the source code
; https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/include/SciLexer.h
; starting from SCE_USER_STYLE_DEFAULT

; The regular expression syntax is explained at
; https://npp-user-manual.org/docs/searching/#regular-expressions

; For example:
;
; [markdown (preinstalled)]
; ; changes the default color - useless, just to see it works.
; 0x66ad1 = \w+
; excluded_styles = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,21,22,23


[python]
;
0x6C8CF7 = (?:(?:def)\s\w+)\s*\(\K.+?(\)\:)
0x6C8CF7 = (\.)?[0-9]+((\.)[0.9]+)?(e[0-9]+)?
;
0x00FFFF = (\*|\*\*)\w+
;
0x8DE8C3 = \b(d)\b
;
0xFFDD89 = \K\w+\ *\(

0xFFDD89 = \b\w+\.
0x7871F0 = \b(cls|self)\b
;
0xFF8000 = \b(e)\b
;
0xEA92C7 = \b(list|map|set|dict|str)\b
0xFF8000 = \_\_[\w\_]+\_\_
;
0x7A6E54 = \.\K\w+



excluded_styles = 1,3,4,6,7,12,16,17,18,19


[c]
; LABEL AND CASE!!!!
; 0xFF8000
;0xFF00FF = (case\s+)?\K(\w+\s*\:)[^:]
0xFF00FF = (case\s+)?\K(\w+\s*)(?=:)
0xFF00FF = (goto\s+)\K(\w+\s*)

; PRE-DEFINESS
0x7871F0 = \_*([A-Z]+\_+)+[A-Z]*
0x993399 = \w+\_t\s+

; typename COOL ALIAS_NAME
0x00FFFF = (typedef)\s*(\S+\s*)\s*\b\K\S+\b

; p_parameter
0x6C8CF7 = \bp_(\w+)\b
;0x6C8CF7 = \w+\s*\(\K(\s*\S+,\s*)*\S+\s*(?=\))


; Static/Global Variables 
; - s_static 
; - c_static 
; - g_global
0x00FFFF = \b((s|c|g)_(\w+))\b
; Public Variable
; m_member
; _member
; .member
0x7A6E54 = \b(m?)_(\w+)\b
0x7A6E54 = \.\K\w+

;0x8DE8C3 = \b(d)\b
; Function
0xFFDD89 = \K\w+\s*(?=\()

;0xEA92C7 = \b(list|map|set|dict|str)\b

; since C++ uses style#11 for "default" text (see name="cpp" section of stylers.xml)
; you would have to remove 11 from the list of excluded_styles
excluded_styles = 1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,20,21,22,23


[c++]
; LABEL AND CASE!!!!
; 0xFF8000
;0xFF00FF = (case\s+)?\K(\w+\s*\:)[^:]
0xFF00FF = (case\s+)?\K(\w+\s*)(?=:)
0xFF00FF = (goto\s+)\K(\w+\s*)

; PRE-DEFINESS
0x7871F0 = \_*([A-Z]+\_+)+[A-Z]*
0x993399 = \w+\_t\s+

; std::
0x7871F0 = (\w+)\s*(?=::.*$)
0x7871F0 = (namespace)\s+\K(\w+)
; std::array
; std::chrono::duration
0x00FFFF = (\w+\s*)(\:\:\s*\w+\s*)*\:\:\s*(\K\w+)
; class ClassName
0x00FFFF = ((typename|class|struct|union)\s+)\b\K\w+\b
; typename COOL ALIAS_NAME
0x00FFFF = (typedef)\s*(\S+\s*)\s*\b\K\S+\b
; <t>
0x00FFFF = \w+[\<]\s*(\K\S+)\s*(?=[\>])
0x00FFFF = \w+[\<]\s*(\K(\S+\s*\,)*\s*\S+)\s*(?=[\>])

; p_parameter
0x6C8CF7 = \bp_(\w+)\b
;0x6C8CF7 = \w+\s*\(\K(\s*\S+,\s*)*\S+\s*(?=\))


; Static/Global Variables 
; - s_static 
; - c_static 
; - g_global
0x00FFFF = \b((s|c|g)_(\w+))\b
; Public Variable
; m_member
; _member
; .member
0x7A6E54 = \b(m?)_(\w+)\b
0x7A6E54 = \.\K\w+

;0x8DE8C3 = \b(d)\b
; Function
0xFFDD89 = \K\w+\s*(?=\()

;0xEA92C7 = \b(list|map|set|dict|str)\b

; since C++ uses style#11 for "default" text (see name="cpp" section of stylers.xml)
; you would have to remove 11 from the list of excluded_styles
excluded_styles = 1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,20,21,22,23



[javascript]
0xFF00FF = \[\K\s*\w+\s*(?=\])
0x00FFFF = \w+(?=\.{1)
0xFFDD89 = \K\w+\s*(?=\()
0xFFDD89 = (\w+)\s*\=\s*(?=(function))
0xFFDD89 = (function\s+)\K(\w+)\(
0x6C8CF7 = function\s*\K\((\w+\,\s*)*\s*\w+\s*\)
0x6C8CF7 = function\s+\w+\s*\K\((\w+\,\s*)*\s*\w+\s*\)
0x6C8CF7 = \[\K\s*\w+\s*(?=\])
; Members
0x7A6E54 = (\w+\.)+\K\w+
0xFFDD89 = \w+\.\K\w+\(
[normal text]
; color each word, 0x66ad1 is the color used, see the description above for more information on the color coding.
0xFFFFFF = \w+
; check in the respective styler xml if the following IDs are valid
excluded_styles = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,21,22,23
